import { Lesson } from '../types';

export const LESSONS: Lesson[] = [
  // TẬP 1
  {
    id: 'tv2_kn_t1_b1',
    title: 'Bài 1: Tôi là học sinh lớp 2',
    level: 1,
    volume: 1,
    text: 'Ngày khai trường đã đến. Sáng sớm, mẹ mới gọi một câu mà tôi đã vùng dậy, khác hẳn mọi ngày. Loáng một cái, tôi đã chuẩn bị xong mọi thứ. Bố ngạc nhiên nhìn tôi, còn mẹ cười tủm tỉm. Tôi rối rít: "Con muốn đến sớm nhất lớp.".\nTôi háo hức tưởng tượng ra cảnh mình đến đầu tiên, cất tiếng chào thật to những bạn đến sau. Nhưng vừa đến cổng trường, tôi đã thấy mấy bạn cùng lớp đang ríu rít nói cười ở trong sân. Thì ra, không chỉ mình tôi muốn đến sớm nhất. Tôi chào mẹ, chạy ào vào cùng các bạn.',
  },
  {
    id: 'tv2_kn_t1_b2',
    title: 'Bài 2: Ngày hôm qua đâu rồi?',
    level: 1,
    volume: 1,
    text: 'Em cầm tờ lịch cũ:\n– Ngày hôm qua đâu rồi?\nRa ngoài sân hỏi bố\nXoa đầu em, bố cười:\n\n– Ngày hôm qua ở lại\nTrên cành hoa trong vườn\nNụ hồng lớn lên mãi\nĐợi đến ngày toả hương.\n\n– Ngày hôm qua ở lại\nTrong hạt lúa mẹ trồng\nCánh đồng chờ gặt hái\nChín vàng màu ước mong.\n\n– Ngày hôm qua ở lại\nTrong vở hồng của con\nCon học hành chăm chỉ\nLà ngày qua vẫn còn.',
  },
  {
    id: 'tv2_kn_t1_b3',
    title: 'Bài 3: Niềm vui của Bi và Bống',
    level: 1,
    volume: 1,
    text: 'Khi cơn mưa vừa dứt, hai anh em Bi và Bống chợt thấy cầu vồng.\n– Cầu vồng kia! Em nhìn xem. Đẹp quá!\nBi chỉ lên bầu trời và nói tiếp:\n– Anh nghe nói dưới chân cầu vồng có bảy hũ vàng đấy.\nBống hưởng ứng:\n– Lát nữa, mình sẽ đi lấy về nhé! Có vàng rồi, em sẽ mua nhiều búp bê và quần áo đẹp.\n– Còn anh sẽ mua một con ngựa hồng và một cái ô tô.\nBỗng nhiên, cầu vồng biến mất. Bi cười:\n– Em ơi! Anh đùa đấy! Ở đó không có vàng đâu.',
  },
  {
    id: 'tv2_kn_t1_b4',
    title: 'Bài 4: Làm việc thật là vui',
    level: 1,
    volume: 1,
    text: 'Quanh ta, mọi vật, mọi người đều làm việc.\nCái đồng hồ tích tắc, tích tắc, báo phút, báo giờ. Con gà trống gáy vang ò ó o, báo cho mọi người biết trời sắp sáng, mau mau thức dậy. Con tu hú kêu tu hú, tu hú. Thế là sắp đến mùa vải chín. Chim bắt sâu, bảo vệ mùa màng. Cành đào nở hoa cho sắc xuân thêm rực rỡ, ngày xuân thêm tưng bừng. Chim cú mèo chập tối đúng trong hốc cây rúc cú cú cũng làm việc có ích cho đồng ruộng.\nNhư mọi vật, mọi người, bé cũng làm việc. Bé làm bài. Bé đi học. Học xong, bé quét nhà, nhặt rau, chơi với em đỡ mẹ. Bé luôn luôn bận rộn, mà lúc nào cũng vui.',
  },
  {
    id: 'tv2_kn_t1_b5',
    title: 'Bài 5: Em có xinh không?',
    level: 1,
    volume: 1,
    text: 'Voi em thích mặc đẹp và thích được khen xinh. Ở nhà, voi em luôn hỏi anh: "Em có xinh không?". Voi anh bao giờ cũng khen: "Em xinh lắm!".\nMột hôm, gặp hươu, voi em hỏi:\n– Em có xinh không?\nHươu ngắm voi rồi lắc đầu:\n– Chưa xinh lắm vì em không có đôi sừng giống anh.\nNghe vậy, voi nhặt vài cành cây khô, gài lên đầu rồi đi tiếp.\nGặp dê, voi hỏi:\n– Em có xinh không?\n– Không, vì cậu không có bộ râu giống tôi.\nVoi liền nhổ một khóm cỏ dại bên đường, gắn vào cằm rồi về nhà. Về nhà với đôi sừng và bộ râu giả, voi em hớn hở hỏi anh:\n– Em có xinh hơn không?\nVoi anh nói:\n– Trời ơi, sao em lại thêm sừng và râu thế này? Xấu lắm!\nVoi em ngắm mình trong gương và thấy xấu thật. Sau khi bỏ sừng và râu đi, voi em thấy mình xinh đẹp hẳn lên. Giờ đây, voi em hiểu rằng mình chỉ xinh đẹp khi đúng là voi.',
  },
  {
    id: 'tv2_kn_t1_b6',
    title: 'Bài 6: Một giờ học',
    level: 2,
    volume: 1,
    text: 'Thầy giáo nói: “Chúng ta cần học cách giao tiếp tự tin. Vì thế hôm nay chúng ta sẽ tập nói trước lớp về bất cứ điều gì mình thích.”.\nQuang được mời lên nói đầu tiên. Cậu lúng túng, đỏ mặt. Quang cảm thấy nói với bạn bên cạnh thì dễ, nhưng nói trước cả lớp thì sao mà khó thế. Thầy bảo: “Sáng nay ngủ dậy, em đã làm gì? Em có nhớ xem.”.\nQuang ngập ngừng, vừa nói vừa gãi đầu: “Em…”.\nThầy giáo nhắc: “Rồi gì nữa?”.\nQuang lại gãi đầu: “À… ờ… Em ngủ dậy.”. Và cậu nói tiếp: “Rồi… ờ…”.\nThầy giáo mỉm cười, kiên nhẫn nghe Quang nói. Thầy bảo: “Thế là được rồi đấy!”.\nQuang chưa chịu về chỗ. Bỗng cậu nói to: “Rồi sau đó… ờ… à…”. Quang thở mạnh một hơi rồi nói tiếp: “Mẹ… ờ… bảo: Con đánh răng đi. Thế là em đánh răng.”. Thầy giáo vỗ tay. Cả lớp vỗ tay theo. Cuối cùng, Quang nói với giọng rất tự tin: “Sau đó bố đưa em đi học.”.\nThầy giáo vỗ tay. Các bạn vỗ tay theo. Quang cũng vỗ tay. Cả lớp tràn ngập tiếng vỗ tay.',
  },
  {
    id: 'tv2_kn_t1_b7',
    title: 'Bài 7: Cây xấu hổ',
    level: 2,
    volume: 1,
    text: 'Bỗng dưng, gió ào ào nổi lên. Có tiếng động gì lạ lắm. Những chiếc lá khô lạt xạt lướt trên cỏ. Cây xấu hổ co rúm mình lại.\nNó bỗng thấy xung quanh xôn xao. Nó hé mắt nhìn: không có gì lạ cả. Bấy giờ, nó mới mở bừng những con mắt lá. Quả nhiên, không có gì lạ thật.\nNhưng những cây cỏ xung quanh vẫn cứ xôn xao. Thì ra, vừa có một con chim xanh biếc, toàn thân lóng lánh như tự toả sáng không biết từ đâu bay tới. Chim đậu một thoáng trên cành thanh mai rồi lại vội bay đi. Các cây cỏ xuýt xoa: biết bao nhiêu con chim đã bay qua đây, chưa có con nào đẹp đến thế.\nCàng nghe bạn bè trầm trồ, cây xấu hổ càng tiếc. Không biết bao giờ con chim xanh ấy quay trở lại?',
  },
  {
    id: 'tv2_kn_t1_b8',
    title: 'Bài 8: Cầu thủ dự bị',
    level: 2,
    volume: 1,
    text: 'Nhìn các bạn đá bóng, gấu con rất muốn chơi cùng. Nhưng thấy gấu con có vẻ chậm chạp và đá bóng không tốt nên chưa đội nào muốn nhận cậu.\n– Gấu à, cậu làm cầu thủ dự bị nhé! – Khi nói.\nGấu con hơi buồn nhưng cũng đồng ý. Trong khi chờ được vào sân, gấu đi nhặt bóng cho các bạn. Gấu cố gắng chạy thật nhanh để các bạn không phải chờ lâu.\nHằng ngày, gấu đến sân bóng từ sớm để luyện tập. Gấu đá bóng ra xa, chạy đi nhặt rồi đá vào gôn, đá đi đá lại,… Cứ thế, gấu đá bóng ngày càng giỏi hơn.\nMột hôm, đến sân bóng thấy gấu đang luyện tập, các bạn ngạc nhiên nhìn gấu rồi nói: “Cậu giỏi quá!”, “Này, vào đội tớ nhé!”, “Vào đội tớ đi!”.\n– Tớ nên vào đội nào đây? – Gấu hỏi khẽ.\n– Hiệp đầu cậu đá cho đội đỏ, hiệp sau cậu đá cho đội xanh. – Khi nói.\nGấu vui vẻ gật đầu. Cậu nghĩ: “Hoá ra làm cầu thủ dự bị cũng hay nhỉ!”.',
  },
  {
    id: 'tv2_kn_t1_b9',
    title: 'Bài 9: Cô giáo lớp em',
    level: 2,
    volume: 1,
    text: 'Sáng nào em đến lớp\nCũng thấy cô đến rồi.\nĐáp lời "Chào cô ạ!"\nCô mỉm cười thật tươi.\n\nCô dạy em tập viết\nGió đưa thoảng hương nhài\nNắng ghé vào cửa lớp\nXem chúng em học bài.\n\nNhững lời cô giáo giảng\nẤm trang vở thơm tho\nYêu thương em ngắm mãi\nNhững điểm mười cô cho.',
  },
  {
    id: 'tv2_kn_t1_b10',
    title: 'Bài 10: Thời khoá biểu',
    level: 1,
    volume: 1,
    text: 'Thời khoá biểu cho biết thời gian học các môn của từng ngày trong tuần. Thời khoá biểu gồm nhiều cột dọc và nhiều hàng ngang. Các bạn học sinh thường đọc thời khoá biểu theo trình tự thứ – buổi – tiết – môn.',
  },
  {
    id: 'tv2_kn_t1_b11',
    title: 'Bài 11: Cái trống trường em',
    level: 2,
    volume: 1,
    text: 'Cái trống trường em\nMùa hè cũng nghỉ\nSuốt ba tháng liền\nTrống nằm ngẫm nghĩ.\n\nBuồn không hả trống\nTrong những ngày hè\nBọn mình đi vắng\nChỉ còn tiếng ve?\n\nCái trống lặng im\nNghiêng đầu trên giá\nChắc thấy chúng em\nNó mừng vui quá!\n\nKia trống đang gọi:\nTùng! Tùng! Tùng!\nVào năm học mới\nGiọng vang tưng bừng.',
  },
  {
    id: 'tv2_kn_t1_b12',
    title: 'Bài 12: Danh sách học sinh',
    level: 2,
    volume: 1,
    text: 'Hôm nay, chúng tôi được đọc truyện tại lớp. Cô giáo cho chúng tôi đăng kí đọc truyện theo sở thích. Dưới đây là danh sách đăng kí của tổ tôi.\nDựa vào danh sách đăng kí, cô chia lớp thành ba nhóm, mỗi nhóm đọc một truyện. Chúng tôi đọc truyện tại lớp. Cô giáo cho chúng tôi đăng kí đọc truyện theo sở thích. Dưới đây là danh sách đăng kí của tổ tôi.',
  },
  {
    id: 'tv2_kn_t1_b13',
    title: 'Bài 13: Yêu lắm trường ơi!',
    level: 2,
    volume: 1,
    text: 'Em yêu mái trường\nCó hàng cây mát\nXôn xao khúc nhạc\nTiếng chim xanh trời.\n\nMỗi giờ ra chơi\nSân trường nhộn nhịp\nHồng hào gương mặt\nBạn nào cũng xinh.\n\nYêu lớp học em\nCó khung cửa sổ\nCó bàn tay lá\nQuạt gió mát vào.\n\nLời cô ngọt ngào\nThấm từng trang sách\nNgày không đến lớp\nThấy nhớ nhớ ghê!\n\nCô đếm trong mơ\nBỗng cười khúc khích\nNgỡ đang ở lớp\nCùng bạn đùa vui.',
  },
  {
    id: 'tv2_kn_t1_b14',
    title: 'Bài 14: Em học vẽ',
    level: 2,
    volume: 1,
    text: 'Hôm nay trong lớp học\nVới giấy trắng, bút màu\nNắn nót em ngồi vẽ\nLung linh bầu trời sao.\n\nVẽ ông trăng trên cao\nRải ánh vàng đầy ngõ\nVẽ cánh diều no gió\nVi vu giữa trời xanh.\n\nVẽ biển cả trong lành\nCó một con thuyền trắng\nGiương cánh buồm đỏ thắm\nĐang rẽ sóng ra khơi.\n\nVẽ cả ông mặt trời\nVà những chùm phượng đỏ\nTrên sân trường lộng gió\nGọi ve về râm ran.',
  },
  {
    id: 'tv2_kn_t1_b15',
    title: 'Bài 15: Cuốn sách của em',
    level: 2,
    volume: 1,
    text: 'Mỗi cuốn sách có một tên riêng. Tên sách là hàng chữ lớn ở khoảng giữa bìa sách, thường chứa đựng nhiều ý nghĩa. Qua tên sách, em có thể biết được sách viết về điều gì.\nNgười viết cuốn sách được gọi là tác giả. Tên tác giả thường được ghi vào phía trên của bìa sách.\nNơi các cuốn sách ra đời được gọi là nhà xuất bản. Tên nhà xuất bản thường được ghi ở phía dưới bìa sách.\nPhần lớn các cuốn sách đều có mục lục thể hiện các mục chính và vị trí của chúng trong cuốn sách. Mục lục thường được đặt ở ngay sau trang bìa, cũng có khi được đặt ở cuối sách.\nMỗi lần đọc một cuốn sách mới, đừng quên những điều này em nhé.',
  },
  {
    id: 'tv2_kn_t1_b16',
    title: 'Bài 16: Khi trang sách mở ra',
    level: 2,
    volume: 1,
    text: 'Khi trang sách mở ra\nChân trời xa xích lại\nBắt đầu là cỏ dại\nThứ đến là cánh chim\nSau nữa là trẻ con\nCuối cùng là người lớn.\n\nTrong trang sách có biển\nEm thấy những cánh buồm\nTrong trang sách có rừng\nVới bao nhiêu là gió.\n\nTrang sách còn có lửa\nMà giấy chẳng cháy đâu\nTrang sách có ao sâu\nMà giấy không hề ướt.\n\nTrang sách không nói được\nSao em nghe điều gì\nDạt dào như sóng vỗ\nMột chân trời đang đi.',
  },
  {
    id: 'tv2_kn_t1_b17',
    title: 'Bài 17: Gọi bạn',
    level: 2,
    volume: 1,
    text: 'Tự xa xưa thuở nào\nTrong rừng xanh sâu thẳm\nĐôi bạn sống bên nhau\nBê vàng và dê trắng.\n\nMột năm, trời hạn hán\nSuối cạn, cỏ héo khô\nLấy gì nuôi đôi bạn\nChờ mưa đến bao giờ?\n\nBê vàng đi tìm cỏ\nLang thang quên đường về\nDê trắng thương bạn quá\nChạy khắp nẻo tìm bê\nĐến bây giờ dê trắng\nVẫn gọi hoài: "Bê! Bê!".',
  },
  {
    id: 'tv2_kn_t1_b18',
    title: 'Bài 18: Tớ nhớ cậu',
    level: 2,
    volume: 1,
    text: 'Kiến là bạn thân của Sóc. Hằng ngày, hai bạn thường rủ nhau đi học. Thế rồi nhà Kiến chuyển đến một khu rừng khác. Lúc chia tay, Kiến rất buồn. Kiến nói: "Cậu phải thường xuyên nhớ tớ đấy.".\nSóc gật đầu nhận lời. Một buổi sáng, Sóc lấy một tờ giấy và viết thư cho Kiến. Sóc nắn nót ghi: "Tớ nhớ cậu.". Mợt con gió đi ngang qua mang theo lá thư. Chiều hôm đó, Kiến đi dạo trong rừng. Một lá thư nhẹ nhàng bay xuống. Kiến reo lên: "A, thư của Sóc!".\nHôm sau, Kiến ngồi bên thềm và viết thư cho Sóc. Kiến không biết làm sao cho Sóc biết mình rất nhớ bạn. Cậu viết: "Chào Sóc!". Nhưng Kiến không định chào Sóc. Cậu bèn viết một lá thư khác: "Sóc thân mến!". Như thế vẫn không đúng ý của Kiến. Lấy một tờ giấy mới, Kiến ghi: "Sóc ơi!". Thế là, cậu cặm cụi viết đi viết lại trong nhiều giờ liền.\nKhông lâu sau, Sóc nhận được một lá thư do Kiến gửi đến. Thư viết: "Sóc ơi, tớ cũng nhớ cậu!".',
  },
  {
    id: 'tv2_kn_t1_b19',
    title: 'Bài 19: Chữ A và những người bạn',
    level: 3,
    volume: 1,
    text: 'Tôi là chữ A. Từ lâu, tôi đã nổi tiếng. Hễ nhắc đến tên tôi, ai cũng biết. Khi vui sướng quá, người ta thường reo lên tên tôi. Khi ngạc nhiên, sững sờ, người ta cũng gọi tên tôi.\nTôi đứng đầu bảng chữ cái tiếng Việt. Trong bảng chữ cái của nhiều nước, tôi cũng được người ta trân trọng xếp ở đầu hàng. Hằng năm, cứ đến ngày khai trường, rất nhiều trẻ em làm quen với tôi trước tiên.\nTôi luôn mơ ước mình tôi làm ra một cuốn sách. Nhưng rồi, tôi nhận ra rằng, nếu chỉ một mình, tôi chẳng thể nói được với ai điều gì. Một cuốn sách chỉ toàn chữ A không thể là cuốn sách mà mọi người muốn đọc. Để có cuốn sách hay, tôi cần các bạn B, C, D, Đ, E,...\nChúng tôi luôn ở bên nhau và cần có nhau trên những trang sách.\nCác bạn nhỏ hãy gặp chúng tôi hằng ngày nhé!',
  },
  {
    id: 'tv2_kn_t1_b20',
    title: 'Bài 20: Nhím nâu kết bạn',
    level: 3,
    volume: 1,
    text: 'Trong khu rừng nọ, có chú nhím nâu hiền lành, nhút nhát. Một buổi sáng, chú đang kiếm quả cây thì thấy nhím trắng chạy tới. Nhím trắng vốn vã: "Chào bạn! Rất vui được gặp bạn!". Nhím nâu lúng túng, nói lí nhí: "Chào bạn!", rồi nấp vào bụi cây. Chú cuộn tròn người lại mà vẫn sợ hãi.\nMùa đông đến, nhím nâu đi tìm nơi để trú ngụ. Bất chợt, mưa kéo đến. Nhím nâu vội bước vào cái hang nhỏ. Thì ra là nhà nhím trắng. Nhím trắng run run: "Xin lỗi, tôi không biết đây là nhà của bạn.". Nhím trắng tươi cười: "Đừng ngại! Gặp lại bạn, tôi rất vui. Tôi ở đây một mình, buồn lắm. Bạn ở lại cùng tôi nhé!".\n"Nhím trắng tốt bụng quá. Bạn ấy nói đúng, không có bạn bè thì thật buồn.". Nghĩ thế, nhím nâu mạnh dạn hẳn lên. Chú nhận lời kết bạn với nhím trắng. Cả hai cùng thu dọn, trang trí chỗ ở cho đẹp. Chúng trải qua những ngày vui vẻ, ấm áp vì không phải sống một mình giữa mùa đông lạnh giá.',
  },
  {
    id: 'tv2_kn_t1_b21',
    title: 'Bài 21: Thả diều',
    level: 3,
    volume: 1,
    text: '(Trích)\nCánh diều no gió\nSáo nó thổi vang\nSao trời trôi qua\nDiều thành trăng vàng.\n\nCánh diều no gió\nTiếng nó trong ngần\nDiều hay chiếc thuyền\nTrôi trên sông Ngân.\n\nCánh diều no gió\nTiếng nó chói chang\nDiều là hạt cau\nPhơi trên nong trời.\n\nTrời như cánh đồng\nXong mùa gặt hái\nDiều em – lưỡi liềm\nAi quên bỏ lại.',
  },
  {
    id: 'tv2_kn_t1_b22',
    title: 'Bài 22: Tớ là lê-gô',
    level: 3,
    volume: 1,
    text: 'Tớ là lê-gô. Nhiều bạn gọi tớ là đồ chơi lắp ráp. Các bạn có nhận ra tớ không?\nĐể tớ giới thiệu với các bạn về gia đình của tớ nhé. Tớ có rất nhiều anh chị em. Chúng tớ là những khối nhỏ đầy màu sắc. Hầu hết chúng tớ có hình viên gạch. Một số thành viên có hình nhân vật tí hon và các hình xinh xắn khác.\nTừ những mảnh ghép nhỏ bé, chúng tớ kết hợp với nhau để tạo ra cả một thế giới diệu kì. Các bạn có thể lắp ráp nhà cửa, xe cộ, người máy,... theo ý thích. Sau đó, các bạn tháo rời ra để ghép thành những vật khác.\nChúng tớ giúp các bạn có trí tưởng tượng phong phú, khả năng sáng tạo và tính kiên nhẫn.\nNào, các bạn đã sẵn sàng chơi cùng chúng tớ chưa?',
  },
  {
    id: 'tv2_kn_t1_b23',
    title: 'Bài 23: Rồng rắn lên mây',
    level: 2,
    volume: 1,
    text: 'Rồng rắn lên mây là một trò chơi vui nhộn. Năm, sáu bạn túm áo nhau làm rồng rắn. Một bạn làm thầy thuốc, đứng đối diện với rồng rắn.\nRồng rắn vừa đi vòng vèo vừa hát:\nRồng rắn lên mây\nThấy cây núc nác\nHỏi thăm thầy thuốc\nCó nhà hay không?\nNếu thầy nói “không” thì rồng rắn đi tiếp. Nếu thầy nói “có” thì rồng rắn hỏi xin thuốc cho con và đồng ý cho thầy bắt khúc đuôi.\nThầy thuốc tìm cách bắt khúc đuôi. Bạn làm đầu dang tay cản thầy thuốc, bạn làm đuôi tìm cách tránh thầy. Nếu bạn khúc đuôi để thầy bắt được thì đổi vai làm thầy thuốc. Nếu bạn khúc giữa để đứt thì đổi vai làm đuôi. Trò chơi cứ thế tiếp tục.',
  },
  {
    id: 'tv2_kn_t1_b24',
    title: 'Bài 24: Nặn đồ chơi',
    level: 2,
    volume: 1,
    text: 'Bên thềm gió mát,\nBé nặn đồ chơi.\nMèo nằm vẫy đuôi,\nTròn xoe đôi mắt.\n\nĐây là quả thị,\nĐây là quả na,\nQuả này phần mẹ,\nQuả này phần cha.\n\nĐây chiếc cối nhỏ\nBé nặn thật tròn,\nBiếu bà đấy nhé,\nGiã trầu thêm ngon.\n\nĐây là thằng chuột\nTặng riêng chú mèo,\nMèo ta thích chí\nVểnh râu “meo meo”!\n\nNgoài hiên đã nắng,\nBé nặn xong rồi.\nĐừng sờ vào đấy,\nBé còn đang phơi.',
  },
  {
    id: 'tv2_kn_t1_b25',
    title: 'Bài 25: Sự tích hoa tỉ muội',
    level: 3,
    volume: 1,
    text: 'Ngày xưa, có hai chị em Nết và Na mồ côi cha mẹ, sống trong ngôi nhà nhỏ bên sườn núi. Nết thương Na, cái gì cũng nhường em. Đêm đông, gió ù ù lùa vào nhà, Nết vòng tay ôm em:\n– Em rét không?\nNa ôm choàng lấy chị, cười rúc rích:\n– Ấm quá!\nNết ôm em chặt hơn, thầm thì:\n– Mẹ bảo chị em mình là hai bông hoa hồng, chị là bông to, em là bông nhỏ. Chị em mình mãi bên nhau nhé!\nNa gật đầu. Hai chị em cứ thế ôm nhau ngủ.\nNăm ấy, nước lũ dâng cao, Nết cõng em chạy theo dân làng đến nơi an toàn. Hai bàn chân Nết rớm máu. Thấy vậy, Bụt thương lắm. Bụt liền phẩy chiếc quạt thần. Kì lạ thay, bàn chân Nết bỗng lành hẳn. Nơi bàn chân Nết đi qua mọc lên những khóm hoa đỏ thắm. Hoa kết thành chùm, bông hoa lớn che chở cho nụ hoa bé nhỏ. Chúng cũng đẹp như tình chị em của Nết và Na.\nDân làng đặt tên cho loài hoa ấy là hoa tỉ muội.',
  },
  {
    id: 'tv2_kn_t1_b26',
    title: 'Bài 26: Em mang về yêu thương',
    level: 2,
    volume: 1,
    text: 'Bé Bo nhà tớ\nrất đáng yêu.\nMẹ, mẹ ơi em bé\nTừ đâu đến nhà ta\nNụ cười như tia nắng\nBàn tay như nụ hoa\nBước chân đi lẫm chẫm\nTiếng cười vang sân nhà?\n\nHay bé từ sao xuống\nHay từ biển bước lên\nHay bé trong quả nhãn\nÔng trồng cạnh hàng hiên?\n\nHay bé theo cơn gió\nNằm cuộn tròn trong mây\nRồi biến thành giọt nước\nRơi xuống nhà mình đây?\n\nMỗi sáng em thức giấc\nLà như thế mây, hoa\nCùng nắng vàng biển rộng\nMang yêu thương vào nhà.',
  },
  {
    id: 'tv2_kn_t1_b27',
    title: 'Bài 27: Mẹ',
    level: 2,
    volume: 1,
    text: 'Lặng rồi cả tiếng con ve\nCon ve cũng mệt vì hè nắng oi.\nNhà em vẫn tiếng ạ ời\nKẽo cà tiếng võng mẹ ngồi mẹ ru.\n\nLời ru có gió mùa thu\nBàn tay mẹ quạt mẹ đưa gió về.\nNhững ngôi sao thức ngoài kia\nChẳng bằng mẹ đã thức vì chúng con.\n\nĐêm nay con ngủ giấc tròn\nMẹ là ngọn gió của con suốt đời.',
  },
  {
    id: 'tv2_kn_t1_b28',
    title: 'Bài 28: Trò chơi của bố',
    level: 2,
    volume: 1,
    text: 'Bố luôn dành cho Hương những điều ngạc nhiên. Lúc rảnh rỗi, hai bố con ngồi chơi với nhau như đôi bạn cùng tuổi.\nCó lần, hai bố con chơi trò chơi “ăn cỗ”. Hương đưa cái bát nhựa cho bố:\n– Mời bác xơi!\nBố đỡ bằng hai tay hẳn hoi và nói:\n– Xin bác. Mời bác xơi!\n– Bác xơi nữa không ạ?\n– Cảm ơn bác! Tôi đủ rồi.\nHai bố con cùng phá lên cười. Lát sau, hai bố con đổi cho nhau. Bố hỏi:\n– Bác xơi gì ạ?\n– Dạ, xin bác bát miến ạ.\n– Đây, mời bác.\nHương đưa tay ra cầm lấy cái bát nhựa. Bố bảo:\n– Ấy, bác phải đỡ bằng hai tay. Tôi đưa cho bác bằng hai tay cơ mà!\nNăm nay, bố đi công tác xa. Đến bữa ăn, nhìn hai bàn tay của Hương lễ phép đón bát cơm, mẹ lại nhớ đến lúc hai bố con chơi với nhau. Mẹ nghĩ, Hương không biết rằng ngay trong trò chơi ấy, bố đã dạy con một nết ngoan.',
  },
  {
    id: 'tv2_kn_t1_b29',
    title: 'Bài 29: Cánh cửa nhớ bà',
    level: 2,
    volume: 1,
    text: 'Ngày cháu còn thấp bé\nCánh cửa có hai then\nCháu chỉ cài then dưới\nNhớ bà cài then trên\n\nMỗi năm cháu lớn lên\nBà lưng còng cắm cúi\nCháu cài được then trên\nBà chỉ cài then dưới...\n\nNay cháu về nhà mới\nBao cánh cửa – ô trời\nMỗi lần tay đẩy cửa\nLại nhớ bà khôn nguôi.',
  },
  {
    id: 'tv2_kn_t1_b30',
    title: 'Bài 30: Thương ông',
    level: 2,
    volume: 1,
    text: '(Trích)\nÔng bị đau chân\nNó sưng nó tấy,\nĐi phải chống gậy\nKhập khiễng, khập khà,\n\nBước lên thềm nhà\nNhấc chân quá khó,\nThấy ông nhăn nhó\nViệt chơi ngoài sân\nLon ton lại gần,\nÂu yếm, nhanh nhảu:\n- Ông vịn vai cháu,\nCháu đỡ ông lên.\n\nÔng bước lên thềm\nTrong lòng sung sướng,\nQuẳng gậy, cúi xuống\nQuên cả đớn đau,\nÔm cháu xoa đầu:\n- Hoan hô thằng bé!\nBé thế mà khoẻ\nVì nó thương ông.',
  },
  {
    id: 'tv2_kn_t1_b31',
    title: 'Bài 31: Ánh sáng của yêu thương',
    level: 3,
    volume: 1,
    text: 'Hôm ấy, bố vắng nhà, mẹ bị đau bụng dữ dội. Ê-đi-xơn liền chạy đi mời bác sĩ.\nBác sĩ đến khám bệnh và cho biết mẹ của Ê-đi-xơn đau ruột thừa, phải mổ gấp. Nhưng trời cứ tối dần, với ánh đèn dầu tù mù, chẳng thể làm gì được. Ê-đi-xơn lo lắng. Thấy mẹ đau đớn, cậu mếu máo: “Xin bác sĩ cứu mẹ cháu!”. Bác sĩ ái ngại nói: “Đủ ánh sáng, bác mới mổ được cháu ạ!”.\nThương mẹ, Ê-đi-xơn ôm đầu suy nghĩ. Làm thế nào để cứu mẹ bây giờ? Đột nhiên, cậu trông thấy ánh sáng của ngọn đèn hắt lại từ mảnh sắt tây trên tủ. Nét mặt cậu rạng rỡ hẳn lên. Ê-đi-xơn vội chạy sang nhà hàng xóm, mượn về một tấm gương. Lát sau, đèn nến trong nhà được cậu thắp lên và đặt trước gương. Căn phòng bỗng ngập tràn ánh sáng.\nNhìn căn phòng sáng trưng, bác sĩ rất ngạc nhiên, bắt tay ngay vào việc. Ca mổ thành công, mẹ của Ê-đi-xơn đã được cứu sống.',
  },
  {
    id: 'tv2_kn_t1_b32',
    title: 'Bài 32: Chơi chong chóng',
    level: 3,
    volume: 1,
    text: 'An yêu thích những chiếc chong chóng giấy. Mỗi chiếc chong chóng chỉ có một cái cán nhỏ và dài, một đầu gắn bốn cánh giấy mỏng, xinh như một bông hoa. Nhưng mỗi lần quay, nó mang lại bao nhiêu là tiếng cười và sự háo hức. An thích chạy thật nhanh để những cánh giấy không ngừng quay trong gió. Gió lướt qua cánh chong chóng tạo ra tiếng u u rất lạ.\nAn thường rủ bé Mai chơi chong chóng và thi xem ai thắng. Hai anh em chạy quanh sân cho chong chóng quay, rồi đột ngột dừng lại. Chong chóng của ai dùng quay trước thì người đó thua. An chạy nhanh hơn nên chong chóng quay lâu hơn. Thua mãi, Mai buồn thiu. An liền cho em giơ chong chóng ra trước quạt máy, còn mình thì phồng má thổi phù phù cho chong chóng quay. Mai cười toe vì thắng. Bây giờ, cũng giống như anh, Mai cũng rất mê những chiếc chong chóng.',
  },

  // TẬP 2
  {
    id: 'tv2_kn_t2_b1',
    title: 'Bài 1: Chuyện bốn mùa',
    level: 2,
    volume: 2,
    text: 'Ngày đầu năm, bốn nàng tiên Xuân, Hạ, Thu, Đông gặp nhau. Đông cầm tay Xuân bảo:\n– Chị là người sung sướng nhất. Ai cũng yêu chị. Chị về, cây nào cũng đâm chồi nảy lộc.\nXuân nói:\n– Nhưng nhờ có em Hạ, cây trong vườn mới đơm trái ngọt, học sinh mới được nghỉ hè.\nNàng Hạ tinh nghịch xen vào:\n– Thế mà thiếu nhi lại thích em Thu nhất. Không có Thu, làm sao có đêm trăng rằm rước đèn, phá cỗ,...\nGiọng buồn buồn, Đông nói:\n– Chỉ có em là chẳng ai yêu.\nThu đặt tay lên vai Đông, thủ thỉ:\n– Có em mới có bập bùng bếp lửa nhà sàn, mọi người mới có giấc ngủ ấm trong chăn.\nBốn nàng tiên mải chuyện trò, không biết bà Đất đã đến từ lúc nào. Bà nói:\n– Xuân làm cho cây lá tươi tốt. Hạ cho trái ngọt, hoa thơm. Thu làm cho trời xanh cao, học sinh nhớ ngày tựu trường. Còn cháu Đông, cháu có công ấp ủ mầm sống để xuân về cây cối đâm chồi nảy lộc. Các cháu đều có ích, đều đáng yêu.',
  },
  {
    id: 'tv2_kn_t2_b2',
    title: 'Bài 2: Mùa nước nổi',
    level: 2,
    volume: 2,
    text: 'Mùa này, người làng tôi gọi là mùa nước nổi, không gọi là mùa nước lũ, vì nước lên hiền hoà. Nước mỗi ngày một dâng lên. Mưa dầm dề, mưa suốt mướt ngày này qua ngày khác.\nRồi đến Rằm tháng Bảy. “Rằm tháng Bảy nước nhảy lên bờ”. Dòng sông Cửu Long đã no đầy, lại tràn qua bờ. Nước trong ao hồ, trong đồng ruộng của mùa mưa hoà lẫn với nước dòng sông Cửu Long.\nĐồng ruộng, vườn tược và cây cỏ như biết giữ lại hạt phù sa ở quanh mình, nước lại trong dần. Ngồi trong nhà, ta thấy cả những đàn cá ròng ròng, từng đàn, từng đàn theo cá mẹ xuôi theo dòng nước, vào tận đồng sâu.\nNgủ một đêm, sáng dậy, nước ngập lên những viên gạch. Phải lấy ván, lấy tre làm cầu từ cửa trước vào đến tận bếp. Vui quá! Có cả một cây cầu lắt lẻo ngay dưới mái nhà.',
  },
  {
    id: 'tv2_kn_t2_b3',
    title: 'Bài 3: Hoạ mi hót',
    level: 2,
    volume: 2,
    text: 'Mùa xuân! Mỗi khi hoạ mi cất lên những tiếng hót vang lừng, mọi vật như có sự thay đổi kì diệu.\nTrời bỗng sáng thêm ra. Những luồng sáng chiếu qua các chùm lộc mới nhú, rực rỡ hơn. Những ngọn sóng trên hồ hoà nhịp với tiếng hoạ mi hót, lấp lánh thêm. Da trời bỗng xanh hơn, những làn mây trắng trắng hơn, xốp hơn, trôi nhẹ nhàng hơn. Các loài hoa nghe tiếng hót trong suốt của hoạ mi chợt bừng giấc, xoè những cánh hoa đẹp, bày đủ các màu sắc xanh tươi. Tiếng hót dìu dặt của hoạ mi giục các loài chim dạo lên những khúc nhạc tưng bừng, ngợi ca núi sông đang đổi mới.\nChim, mây, nước và hoa đều cho rằng tiếng hót kì diệu của hoạ mi đã làm cho tất cả bừng tỉnh giấc... Hoạ mi thấy lòng vui sướng, cố hót hay hơn.',
  },
  {
    id: 'tv2_kn_t2_b4',
    title: 'Bài 4: Tết đến rồi',
    level: 1,
    volume: 2,
    text: 'Tết là khởi đầu cho một năm mới, là dịp lễ được mong chờ nhất trong năm.\nVào dịp Tết, các gia đình thường gói bánh chưng hoặc bánh tét. Bánh chưng hình vuông, gói bằng lá dong. Bánh tét hình trụ, thường gói bằng lá chuối. Cả hai loại bánh đều làm từ gạo nếp, đỗ xanh, thịt lợn.\nMai và đào là những loài hoa đặc trưng cho Tết ở hai miền Nam, Bắc. Hoa mai rực rỡ sắc vàng. Hoa đào thường có màu hồng tươi, xen lẫn lá xanh và nụ hồng chúm chím.\nNgày Tết, người lớn thường tặng trẻ em những bao lì xì xinh xắn, với mong ước các em mạnh khoẻ, giỏi giang. Tết là dịp mọi người quây quần bên nhau và dành cho nhau những lời chúc tốt đẹp.',
  },
  {
    id: 'tv2_kn_t2_b5',
    title: 'Bài 5: Giọt nước và biển lớn',
    level: 1,
    volume: 2,
    text: 'Tí ta tí tách\nTừng giọt\nMưa rơi\nRơi rơi.\nGóp lại bao ngày\nThành dòng suối nhỏ\nLượn trên bãi cỏ\nChảy xuống chân đồi.\n\nSuối gặp bạn rồi\nGóp thành sông lớn\nSông đi ra biển\nBiển thành mênh mông.\n\nBiển ơi, có biết\nBiển lớn vô cùng\nTừng giọt nước trong\nLàm nên biển đấy!',
  },
  {
    id: 'tv2_kn_t2_b6',
    title: 'Bài 6: Mùa vàng',
    level: 2,
    volume: 2,
    text: 'Thu về, những quả hồng đỏ mọng, những hạt dẻ nâu bóng, những quả na mở to mắt, thơm dịu dịu. Biển lúa vàng ươm. Gió nổi lên và sóng lúa vàng dập dờn trải tới chân trời.\nMinh ríu rít bên mẹ:\n– Mẹ ơi, con thấy quả trên cây đều chín hết cả rồi. Các bạn ấy đang mong có người đến hái đấy. Nhìn quả chín ngon thế này, chắc các bác nông dân vui lắm mẹ nhỉ?\n– Đúng thế con ạ.\n– Nếu mùa nào cũng được thu hoạch thì thích lắm, phải không mẹ?\nMẹ âu yếm nhìn Minh và bảo:\n– Con nói đúng đấy! Mùa nào thức ấy.\nNhưng để có sản phẩm thu hoạch, trước đó người nông dân phải làm rất nhiều việc. Họ phải cày bừa, gieo hạt và ươm mầm. Rồi mùa nắng, hạn hán, họ phải chăm sóc vườn cây, ruộng đồng. Nhờ thế mà cây lớn dần, ra hoa kết trái và chín rộ đấy.\n– Mẹ ơi, con hiểu rồi. Công việc của các bác nông dân vất vả quá mẹ nhỉ?',
  },
  {
    id: 'tv2_kn_t2_b7',
    title: 'Bài 7: Hạt thóc',
    level: 2,
    volume: 2,
    text: 'Tôi chỉ là hạt thóc\nSinh ra trên cánh đồng\nGiấu trong mình câu chuyện\nMột cuộc đời bão giông.\n\nTôi ngậm ánh nắng sớm\nTôi uống giọt sương mai\nTôi sống qua bão lũ\nTôi chịu nhiều thiên tai.\n\nDẫu hình hài bé nhỏ\nTôi trải cả bốn mùa\nDẫu bây giờ bình dị\nTôi có từ ngàn xưa.\n\nTôi chỉ là hạt thóc\nKhông biết hát biết cười\nNhưng tôi luôn có ích\nVì nuôi sống con người.',
  },
  {
    id: 'tv2_kn_t2_b8',
    title: 'Bài 8: Luỹ tre',
    level: 3,
    volume: 2,
    text: 'Mỗi sớm mai thức dậy\nLuỹ tre xanh rì rào\nNgọn tre cong gọng vó\nKéo mặt trời lên cao.\n\nNhững trưa đồng đầy nắng\nTrâu nằm nhai bóng râm\nTre bần thần nhớ gió\nChợt về đầy tiếng chim.\n\nMặt trời xuống núi ngủ\nTre nâng vầng trăng lên\nSao, sao treo đầy cành\nSuốt đêm dài thắp sáng.\n\nBỗng gà lên tiếng gáy\nXôn xao ngoài luỹ tre\nĐêm chuyển dần về sáng\nMầm măng đợi nắng về.',
  },
  {
    id: 'tv2_kn_t2_b9',
    title: 'Bài 9: Ve chim',
    level: 3,
    volume: 2,
    text: 'Hay chạy lon xon\nLà gà mới nở\nVừa đi vừa nhảy\nLà em sáo xinh\nHay nói linh tinh\nLà con liếu điếu\nHay nghịch hay tếu\nLà cậu chìa vôi\nHay chao đớp mồi\nLà chim chèo bẻo\nTính hay mách lẻo\nThím khách trước nhà\nHay nhặt lân la\nLà bà chim sẻ\nCó tình có nghĩa\nLà mẹ chim sâu\nGiục hè đến mau\nLà cô tu hú\nNhấp nhem buồn ngủ\nLà bác cú mèo...',
  },
  {
    id: 'tv2_kn_t2_b10',
    title: 'Bài 10: Khủng long',
    level: 2,
    volume: 2,
    text: 'Khủng long là loài vật thường sống thành bầy đàn ở các vùng đất khô.\nTrong suy nghĩ của nhiều người, khủng long là loài vật khổng lồ. Nhưng trên thực tế, có loài khủng long chỉ bằng một chú chó nhỏ. Khủng long thường ăn thịt, cũng có một số loài ăn cỏ.\nChân khủng long thẳng và rất khoẻ. Vì thế chúng có thể đi khắp một vùng rộng lớn để kiếm ăn. Khủng long có khả năng săn mồi tốt nhờ có đôi mắt tinh tường cùng cái mũi và đôi tai thính. Khủng long cũng có khả năng tự vệ tốt nhờ vào cái đầu cứng và cái quật đuôi dũng mãnh.\nTrước khi con người xuất hiện, khủng long đã bị tuyệt chủng. Vì thế, chúng ta sẽ không bao giờ có thể nhìn thấy khủng long thật.',
  },
  {
    id: 'tv2_kn_t2_b11',
    title: 'Bài 11: Sự tích cây thì là',
    level: 3,
    volume: 2,
    text: 'Ngày xưa, cây cối trên trái đất chưa có tên gọi. Trời bèn gọi chúng lên để đặt tên. Cây cối mừng rỡ kéo nhau lên trời. Trời chỉ tay vào từng cây và đặt tên:\n– Chú thì ta đặt tên cho là cây dừa.\n– Chú thì ta đặt tên cho là cây cau.\n– Chú thì ta đặt tên cho là cây mít...\nTrời đặt tên mãi mà vẫn chưa hết. Về sau, Trời chỉ nói vắn tắt:\n– Chú thì là cây cải.\n– Chú là cây ớt.\n– Chú là cây tỏi...\nKhi các loài cây đều đã có tên, bỗng một cái cây dáng mảnh khảnh, lá nhỏ xíu đến xin đặt tên.\n– Chú bé tí xíu, chú có ích gì để ta đặt tên nào? – Trời hỏi.\nCây nhỏ liền thưa:\n– Thưa Trời, khi nấu canh riêu cá hoặc làm chả cá, chả mực mà không có con thì mất cả ngon ạ.\nTrời liền bảo:\n– Ừ, để ta nghĩ cho một cái tên. Tên chú thì... là... thì... là...\nTrời còn đang suy nghĩ, cây nhỏ đã chạy đi xa rồi. Nó mừng rỡ khoe với bạn bè:\n– Trời đặt tên cho tôi là cây “thì là” đấy!',
  },
  {
    id: 'tv2_kn_t2_b12',
    title: 'Bài 12: Bờ tre đón khách',
    level: 2,
    volume: 2,
    text: 'Bờ tre quanh hồ\nSuốt ngày đón khách\nMột đàn cò bạch\nHạ cánh reo mừng\nTre chợt tưng bừng\nNở đầy hoa trắng.\n\nĐến chơi im lặng\nCó bác bồ nông\nĐứng nhìn mênh mông\nIm như tượng đá.\nMột chú bói cá\nĐỗ xuống cành mềm\nChú vút bay lên\nĐậu vào chỗ cũ.\n\nGhé chơi đông đủ\nCả toán chim cu\nCa hát gật gù:\n“Ồ, tre rất mát!”.\n\nKhách còn chú ếch\nÌ ọp vang lừng\nGọi sao tung bừng\nLúc ngày vừa tắt.',
  },
  {
    id: 'tv2_kn_t2_b13',
    title: 'Bài 13: Tiếng chổi tre',
    level: 3,
    volume: 2,
    text: '(Trích)\nNhững đêm hè\nKhi ve ve\nĐã ngủ\nTôi lắng nghe\nTrên đường Trần Phú\nTiếng chổi tre\nXao xác\nHàng me\nTiếng chổi tre\nĐêm hè\nQuét rác...\n\nNhững đêm đông\nKhi con dông\nVừa tắt\nTôi đứng trông\nTrên đường lặng ngắt\nChị lao công\nNhư sắt\nNhư đồng\nChị lao công\nĐêm đông\nQuét rác...\n\nNhớ em nghe\nTiếng chổi tre\nChị quét\nNhững đêm hè\nĐêm đông gió rét\nTiếng chổi tre\nSớm tối\nĐi về\nGiữ sạch lề\nĐẹp lối\nEm nghe!',
  },
  {
    id: 'tv2_kn_t2_b14',
    title: 'Bài 14: Cò non cười rồi',
    level: 3,
    volume: 2,
    text: 'Mùa xuân đã đến. Cỏ trong công viên bừng tỉnh sau giấc ngủ đông. Từng đàn én từ phương Nam trở về. Trẻ em chơi đùa dưới ánh mặt trời ấm áp.\nMột hôm, chị én nâu đang sửa soạn đi ngủ thì nghe thấy tiếng khóc thút thít. Lần theo tiếng khóc, én nâu tìm đến công viên nhỏ. Thấy một cây cỏ non đang khóc, én nâu hỏi:\n– Em bị ốm à?\nCỏ non khóc nấc lên:\n– Chị ơi, em không đứng thẳng được nữa. Các bạn nhỏ đã đến đây chơi đùa và giẫm lên em.\nÉn nâu lặng đi một phút rồi bỗng reo lên:\n– Đừng khóc nữa! Chị sẽ giúp em.\nThế rồi, én nâu gọi thêm rất nhiều bạn của mình. Suốt đêm, cả đàn én ra sức đi tìm cỏ khô tết thành dòng chữ “Không giẫm chân lên cỏ!” đặt bên cạnh bãi cỏ. Xong việc, én nâu tươi cười bảo cỏ non:\n– Từ nay em yên tâm rồi. Không còn ai giẫm lên em nữa đâu.\nCỏ non nhoẻn miệng cười và cảm ơn chị én nâu.',
  },
  {
    id: 'tv2_kn_t2_b15',
    title: 'Bài 15: Những con sao biển',
    level: 3,
    volume: 2,
    text: 'Một người đàn ông đang dạo bộ trên bãi biển khi chiều xuống. Biển đông người, nhưng ông lại chú ý đến một cậu bé cứ liên tục cúi xuống nhặt thứ gì đó rồi thả xuống biển.\nTiến lại gần hơn, ông thấy cậu bé đang nhặt những con sao biển bị thuỷ triều đánh dạt lên bờ và thả chúng trở về với đại dương.\n– Cháu đang làm gì vậy? – Người đàn ông hỏi.\nCậu bé trả lời:\n– Những con sao biển này sắp chết vì thiếu nước, cháu muốn giúp chúng.\n– Có hàng ngàn con sao biển như vậy, liệu cháu có thể giúp được tất cả chúng không?\nCậu bé vẫn tiếp tục nhặt những con sao biển khác thả xuống biển và nói với người đàn ông:\n– Cháu cũng biết như vậy, nhưng ít nhất thì cháu cũng cứu được những con sao biển này.\nNgười đàn ông trìu mến nhìn cậu bé và cùng cậu cứu những con sao biển.',
  },
  {
    id: 'tv2_kn_t2_b16',
    title: 'Bài 16: Tạm biệt cánh cam',
    level: 2,
    volume: 2,
    text: 'Chú cánh cam đi lạc vào nhà Bống. Chân chú bị thương, bước đi tập tễnh. Bống thương quá, đặt cánh cam vào một chiếc lọ nhỏ đựng đầy cỏ. Từ ngày đó, cánh cam trở thành người bạn nhỏ xíu của Bống.\nCánh cam có đôi cánh xanh biếc, óng ánh dưới ánh nắng mặt trời. Mỗi khi nghe tiếng động, chú khệ nệ ôm cái bụng tròn lẳn, trốn vào đám cỏ rối. Bống chăm sóc cánh cam rất cẩn thận. Hằng ngày, em đều bỏ vào chiếc lọ một chút nước và những ngọn cỏ xanh non.\nNhưng Bống cảm thấy cánh cam vẫn có vẻ ngơ ngác không vui, chắc chú nhớ nhà và nhớ bạn bè. Đoán vậy, Bống mang cánh cam thả ra bãi cỏ sau nhà. Tạm biệt cánh cam bé nhỏ, Bống hi vọng chú sẽ tìm được đường về căn nhà thân thương của mình.',
  },
  {
    id: 'tv2_kn_t2_b17',
    title: 'Bài 17: Những cách chào độc đáo',
    level: 2,
    volume: 2,
    text: 'Trên thế giới có những cách chào phổ biến như bắt tay, vẫy tay và cúi chào. Ngoài ra, người ta còn có những cách chào nhau rất đặc biệt.\nNgười Ma-ô-ri ở Niu Di-lân chào bằng cách nhẹ nhàng chạm mũi và trán vào nhau. Người Ấn Độ thì chắp hai tay trước ngực, kèm theo một cái cúi đầu. Nhiều người ở Mỹ thì chào bằng cách nắm bàn tay lại và đấm nhẹ vào nắm tay người kia. Còn người Dim-ba-bu-ê lại chào theo cách truyền thống là vỗ tay,... Mỗi cách chào thể hiện một nét riêng trong giao tiếp của người dân ở từng nước.\nCòn em, em chào bạn bằng cách nào?',
  },
  {
    id: 'tv2_kn_t2_b18',
    title: 'Bài 18: Thư viện biết đi',
    level: 2,
    volume: 2,
    text: 'Thư viện là nơi lưu giữ sách báo, nơi mọi người đến đọc sách hoặc mượn sách về nhà. Nhiều người nghĩ rằng thư viện chỉ nằm im một chỗ. Nhưng trên thế giới, có rất nhiều “thư viện biết đi”.\nThư viện Lô-gô-xơ của Đức là “thư viện nổi” lớn nhất thế giới. Nó nằm trên một con tàu biển khổng lồ, có thể chở được 500 hành khách và đã từng đi qua 45 nước trên thế giới.\nỞ Phần Lan, có hàng trăm “thư viện di động” trên những chiếc xe buýt cũ, chạy khắp các thành phố lớn. Ở châu Phi, một người thủ thư đã đặt thư viện trên lưng một con lạc đà. Nhờ thế, những cuốn sách có thể băng qua sa mạc để đến với người đọc.',
  },
  {
    id: 'tv2_kn_t2_b19',
    title: 'Bài 19: Cảm ơn anh hà mã',
    level: 2,
    volume: 2,
    text: 'Dê rủ cún vào rừng chơi, khi quay về thì bị lạc đường. Gặp cô hươu, dê hỏi:\n– Cô kia, về làng đi lối nào?\n– Không biết. – Hươu lắc đầu, bỏ đi.\nĐi tiếp, tới một con sông, thấy anh hà mã, dê nói to:\n– Bọn tôi muốn về làng, hãy đưa bọn tôi qua sông!\nHà mã phật ý, định bỏ đi. Thấy vậy, cún nói:\n– Chào anh hà mã, anh giúp bọn em qua sông được không ạ?\n– Được chứ! Em ngoan quá! – Hà mã vui vẻ nói.\n– Cảm ơn anh! – Cún đáp rồi quay sang nói nhỏ với dê:\n– Cậu quên lời cô dặn rồi à? Muốn ai đó giúp, phải hỏi một cách lịch sự, còn khi họ giúp mình, phải nói “cảm ơn”.\nDê con hơi xấu hổ. Sang bên kia sông, dê nói với hà mã:\n– Cảm ơn anh đã giúp. Em biết mình sai rồi. Em xin lỗi ạ!\nHà mã mỉm cười:\n– Em biết lỗi là tốt rồi. Giờ các em cứ đi theo đường này là về làng thôi.',
  },
  {
    id: 'tv2_kn_t2_b20',
    title: 'Bài 20: Từ chú bồ câu đến in-tơ-nét',
    level: 2,
    volume: 2,
    text: 'Ngoài trò chuyện trực tiếp, con người còn nghĩ ra rất nhiều cách để trao đổi với nhau khi ở xa.\nTừ xa xưa, người ta đã biết huấn luyện bồ câu để đưa thư. Bồ câu nhớ đường rất tốt. Nó có thể bay qua một chặng đường dài hàng nghìn cây số để mang thư đến đúng nơi nhận.\nNhững người đi biển còn nghĩ ra cách bỏ thư vào trong những chiếc chai thuỷ tinh. Nhờ sóng biển, những chiếc chai này được đẩy vào đất liền. Có những bức thư vài chục năm sau mới được tìm thấy.\nNgày nay, việc trao đổi thông tin dễ dàng hơn rất nhiều. Nhờ có in-tơ-nét, bạn cũng có thể nhìn thấy người nói chuyện với mình, dù hai người đang ở cách nhau rất xa.',
  },
  {
    id: 'tv2_kn_t2_b21',
    title: 'Bài 21: Mai An Tiêm',
    level: 3,
    volume: 2,
    text: 'Ngày xưa, có một người tên là Mai An Tiêm được vua Hùng yêu mến nhận làm con nuôi. Một lần, vì hiểu lầm lời nói của An Tiêm nên nhà vua nổi giận, đày An Tiêm ra đảo hoang.\nỞ đảo hoang, hai vợ chồng An Tiêm dựng nhà bằng tre nứa, lấy cỏ phơi khô tết thành quần áo.\nMột hôm, An Tiêm thấy một đàn chim bay qua thả xuống loại hạt đen nhánh. Chàng bèn nhặt và gieo xuống cát, thầm nghĩ: “Thứ quả này chim ăn được thì người cũng ăn được”. Rồi hạt nảy mầm, vươn thành một loại cây dây bò lan rộng. Cây ra hoa rồi ra quả. Quả có vỏ màu xanh thẫm, ruột đỏ, hạt đen. Vợ chồng An Tiêm đem hạt gieo trồng khắp đảo.\nMùa quả chín, nhớ vua cha, An Tiêm khắc tên mình vào quả, thả xuống biển, nhờ sóng đưa vào đất liền. Một người dân vớt được quả lạ đem dâng vua. Vua hối hận cho đón vợ chồng An Tiêm trở về.\nThứ quả lạ đó là giống dưa hấu ngày nay.',
  },
  {
    id: 'tv2_kn_t2_b22',
    title: 'Bài 22: Thư gửi bố ngoài đảo',
    level: 2,
    volume: 2,
    text: '(Trích)\nBây giờ sắp Tết rồi\nCon viết thư gửi bố (...)\nTết con muốn gửi bố\nCái bánh chưng cho vui\nNhưng bánh thì to quá\nMà hòm thư nhỏ thôi.\n\nNgoài ấy chắc nhiều gió\nĐảo không có gì che\nNgoài ấy chắc nhiều sóng\nBố lúc nào cũng nghe.\n\nGửi hoa lại sợ héo\nĐường ra đảo xa xôi\nCon viết thư gửi vậy\nHẳn bố bằng lòng thôi.\n\nBà bảo: hàng rào biển\nLà bố đấy, bố ơi\nCùng các chú bạn bố\nGiữ đảo và giữ trời.',
  },
  {
    id: 'tv2_kn_t2_b23',
    title: 'Bài 23: Bóp nát quả cam',
    level: 3,
    volume: 2,
    text: 'Giặc Nguyên cho sứ thần sang giả vờ mượn đường để xâm chiếm nước ta. Thấy sứ giặc ngang ngược, Trần Quốc Toản vô cùng căm giận.\nBiết vua họp bàn việc nước dưới thuyền rồng, Quốc Toản muốn được gặp để xin vua quyết đánh. Đợi mãi không gặp được vua, cậu liều chết xô mấy người lính gác, xăm xăm xuống bến.\nGặp vua, Quốc Toản quỳ xuống tâu:\n– Cho giặc mượn đường là mất nước. Xin bệ hạ cho đánh!\nNói xong, cậu tự đặt thanh gươm lên gáy, xin chịu tội.\nVua cho Quốc Toản đứng dậy, ôn tồn bảo:\n– Quốc Toản làm trái phép nước, lẽ ra phải trị tội. Nhưng còn trẻ mà đã biết lo việc nước, ta có lời khen.\nNói rồi, vua ban cho Quốc Toản một quả cam.\nQuốc Toản ấm ức bước lên bờ: “Vua ban cho cam quý nhưng xem ta như trẻ con, không cho dự bàn việc nước.”. Nghĩ đến quân giặc ngang ngược, cậu nghiến răng, hai bàn tay bóp chặt.\nKhi trở ra, Quốc Toản xoè tay cho mọi người xem cam quý. Nhưng quả cam đã nát từ bao giờ.',
  },
  {
    id: 'tv2_kn_t2_b24',
    title: 'Bài 24: Chiếc rễ đa tròn',
    level: 3,
    volume: 2,
    text: 'Một sớm hôm ấy, như thường lệ, Bác Hồ đi dạo trong vườn. Đến gần cây đa, Bác chợt thấy một chiếc rễ đa nhỏ và dài ngoằn ngoèo trên mặt đất. Chắc là trận gió đêm qua đã làm nó rơi xuống. Bác tần ngần một lát, rồi nói với chú cận vụ:\n– Chú cuốn chiếc rễ này lại, rồi trồng cho nó mọc tiếp nhé!\nTheo lời Bác, chú cận vụ xới đất, vùi chiếc rễ xuống. Thấy vậy, Bác ân cần bảo:\n– Chú nên làm thế này.\nNói rồi, Bác cuộn chiếc rễ thành một vòng tròn, cùng chú cận vụ buộc nó tựa vào hai cái cọc, sau đó mới vùi hai đầu rễ xuống đất.\nChú cận vụ thắc mắc:\n– Thưa Bác, Bác làm thế để làm gì ạ?\nBác khẽ cười:\n– Rồi chú sẽ biết.\nNhiều năm sau, chiếc rễ đã lớn và thành cây đa con có vòng lá tròn. Thiếu nhi vào thăm vườn Bác, em nào cũng thích chui qua chui lại vòng lá ấy. Lúc đó, mọi người mới hiểu vì sao Bác cho trồng chiếc rễ đa thành hình tròn như thế.',
  },
  {
    id: 'tv2_kn_t2_b25',
    title: 'Bài 25: Đất nước chúng mình',
    level: 2,
    volume: 2,
    text: 'Việt Nam là đất nước tươi đẹp của chúng mình. Thủ đô nước mình là Hà Nội. Lá cờ Tổ quốc hình chữ nhật, nền đỏ, ở giữa có ngôi sao vàng năm cánh.\nViệt Nam có những vị anh hùng có công lớn với đất nước như Hai Bà Trưng, Bà Triệu, Trần Hưng Đạo, Quang Trung, Hồ Chí Minh,... Những con người ấy đã làm rạng danh lịch sử nước nhà.\nĐất nước mình có ba miền Bắc, Trung, Nam với khí hậu khác nhau. Miền Bắc một năm có bốn mùa: xuân, hạ, thu, đông. Miền Nam có hai mùa: mùa mưa và mùa khô. Miền Trung có nơi giống miền Bắc, có nơi giống miền Nam.\nTrang phục truyền thống của người Việt Nam là áo dài. Áo dài thường được mặc trong dịp Tết hoặc lễ hội.',
  },
  {
    id: 'tv2_kn_t2_b26',
    title: 'Bài 26: Trên các miền đất nước',
    level: 2,
    volume: 2,
    text: 'Đất nước Việt Nam thật tươi đẹp. Hãy cùng nhau đi thăm các miền đất nước qua những câu ca dao.\nĐầu tiên, chúng ta sẽ đến Phú Thọ, miền Bắc nước ta, nơi có đền thờ Vua Hùng, nơi được gọi là “quê cha đất tổ”:\nDù ai đi ngược về xuôi\nNhớ ngày Giỗ Tổ mùng Mười tháng Ba.\nTiếp đến, chúng ta cũng vào miền Trung:\nĐường vô xứ Nghệ quanh quanh\nNon xanh nước biếc như tranh hoạ đồ.\nVà chúng ta cũng ghé thăm miền đất Nam Bộ:\nĐồng Tháp Mười cò bay thẳng cánh\nNước Tháp Mười lóng lánh cá tôm.\nVậy là chúng ta đã đi qua ba miền Bắc, Trung, Nam của đất nước. Nơi nào cũng để lại bao tình cảm mến thương.',
  },
  {
    id: 'tv2_kn_t2_b27',
    title: 'Bài 27: Chuyện quả bầu',
    level: 3,
    volume: 2,
    text: 'Ngày xưa có vợ chồng nọ đi rừng, bắt được một con dúi. Dúi xin tha cho nó. Để trả ơn, dúi báo sắp có lũ lụt rất lớn và chỉ cho họ cách tránh. Họ nói với bà con nhưng chẳng ai tin. Nghe lời dúi, họ khoét rỗng khúc gỗ to, chuẩn bị thức ăn bỏ vào đó. Vừa chuẩn bị xong mọi thứ thì mưa to, gió lớn, nước ngập mênh mông. Muôn loài chìm trong biển nước. Nhờ sống trong khúc gỗ nổi, vợ chồng nhà nọ thoát nạn.\nÍt lâu sau, người vợ sinh ra một quả bầu.\nMột hôm, đi làm nương về, họ nghe tiếng cười đùa từ gác bếp để quả bầu. Thấy lạ, họ lấy quả bầu xuống, áp tai nghe thì có tiếng lao xao. Người vợ bèn lấy que dùi quả bầu. Lạ thay, từ trong quả bầu, những con người bé nhỏ bước ra. Người Khơ Mú ra trước. Tiếp đến, người Thái, người Mường, người Dao, người Mông, người Ê-đê, người Ba-na, người Kinh,... lần lượt ra theo.\nĐó là tổ tiên của các dân tộc anh em trên đất nước ta ngày nay.',
  },
  {
    id: 'tv2_kn_t2_b28',
    title: 'Bài 28: Khám phá đáy biển ở Trường Sa',
    level: 2,
    volume: 2,
    text: 'Nhắc đến Trường Sa, ngoài các đảo, người ta nhắc đến biển. Mà biển thì có muôn vàn điều kì thú. Thám hiểm đáy biển ở Trường Sa của nước ta sẽ thấy bao điều thú vị.\nBiển ở Trường Sa có những loài cá đẹp rực rỡ và lạ mắt. Từng đàn cá đủ màu sắc, dày đặc đến hàng trăm con tạo nên một tấm thảm hoa di động. Những vỉa san hô chạy dài từ chân mỗi đảo xuống sâu dần dưới đáy biển. San hô làm cho đáy biển trông như một bức tranh khổng lồ, đẹp như những toà lâu đài trong truyện cổ tích.\nTrường Sa là vùng biển thân yêu của Tổ quốc, có cảnh đẹp kì thú và hàng nghìn loài vật sống dưới biển.',
  },
  {
    id: 'tv2_kn_t2_b29',
    title: 'Bài 29: Hồ Gươm',
    level: 3,
    volume: 2,
    text: 'Nhà tôi ở Hà Nội, cách Hồ Gươm không xa. Từ trên cao nhìn xuống, mặt hồ như một chiếc gương bầu dục lớn, sáng long lanh.\nCầu Thê Húc màu son, cong cong như con tôm, dẫn vào đền Ngọc Sơn. Mái đền lấp ló bên gốc đa già, rễ lá xum xuê. Xa một chút là Tháp Rùa, tường rêu cổ kính. Tháp xây trên gò đất giữa hồ, cỏ mọc xanh um.\nCó buổi, người ta thấy có con rùa lớn, đầu to như trái bưởi, nhô lên khỏi mặt nước. Rùa như lắng nghe tiếng chuông đồng hồ trên tầng cao nhà bưu điện, buông từng tiếng ngân nga trong gió. Tôi thầm nghĩ: không biết có phải rùa đã từng ngậm thanh gươm của vua Lê thắng giặc đó không?',
  },
  {
    id: 'tv2_kn_t2_b30',
    title: 'Bài 30: Cánh đồng quê em',
    level: 2,
    volume: 2,
    text: 'Bé theo mẹ ra đồng\nVầng dương lên rực đỏ\nMuôn vàn kim cương nhỏ\nLấp lánh ngọn cỏ hoa.\n\nNắng ban mai hiền hoà\nTung lụa tơ vàng óng\nTrải lên muôn con sóng\nDập dờn đồng lúa xanh.\n\nĐàn chiền chiện bay quanh\nHót tích ri tích rích\nLũ châu chấu tinh nghịch\nĐu cỏ uống sương rơi.\n\nSóng xanh cuộn chân trời\nCánh đồng như tranh vẽ\nBé ngân nga hát khẽ\nTrong hương lúa mênh mông.',
  },
];
